benford/urls.py
from django.urls import path

from benford.views import DashboardView, DatasetUploadView, DatasetDetailView, DatasetRowListView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('upload/', DatasetUploadView.as_view(), name='upload_dataset'),
    path('dataset/<slug:slug>/', DatasetDetailView.as_view(), name='dataset_detail'),
    path('dataset/<slug:slug>/browse/', DatasetRowListView.as_view(), name='dataset_rows'),
]

app_name = 'benford'

frankbenford/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    re_path(r'^', include('benford.urls', namespace='benford')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

benford/models.py
from django.db import models
from django.urls import reverse

from benford.utils import generate_random_identifier


class Dataset(models.Model):
    slug = models.CharField(
        max_length=10, unique=True, default=generate_random_identifier)
    title = models.CharField(max_length=50, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    base = models.PositiveSmallIntegerField(default=10)

    def display_title(self):
        return self.title or 'Untitled dataset'

    def get_absolute_url(self):
        return reverse('benford:dataset_detail', kwargs={'slug': self.slug})

    def get_occurences_summary(self):
        return dict((x.digit, x.occurences) for x in self.significant_digits.all())

    class Meta:
        ordering = ['-created_at', ]


class SignificantDigit(models.Model):
    dataset = models.ForeignKey(
        'Dataset', on_delete=models.CASCADE, related_name='significant_digits')
    digit = models.PositiveSmallIntegerField()
    occurences = models.PositiveIntegerField()

    class Meta:
        unique_together = [
            ('dataset', 'digit'),
        ]


class DatasetRow(models.Model):
    dataset = models.ForeignKey(
        'Dataset', related_name='+', on_delete=models.CASCADE)
    line = models.PositiveIntegerField(
        verbose_name='line number',
        db_index=True)
    data = models.JSONField(default=list)
    has_error = models.BooleanField(blank=True, default=False)

    class Meta:
        index_together = [
            ('dataset', 'has_error'),
        ]
        unique_together = [
            ('dataset', 'line'),
        ]

benford/forms.py
import magic
from crispy_forms.layout import Layout, Submit, Field, Div
from django import forms
from pydash import get

from crispy_forms_bootstrap5.forms import CrispyFormMixin


class DatasetUploadForm(CrispyFormMixin, forms.Form):
    title = forms.CharField(required=False, label="Your dataset name")
    data_file = forms.FileField(
        required=False, label="Upload data file...")
    data_raw = forms.CharField(
        label="...or paste your data here",
        widget=forms.Textarea(), required=False,
    )
    relevant_column = forms.IntegerField(
        min_value=0, required=False,
        widget=forms.NumberInput(attrs={'placeholder': 'Auto'}))
    has_header = forms.BooleanField(
        required=False,
        label="Is first row a header?")

    def clean(self):
        data_file = get(self.cleaned_data, 'data_file')
        data_raw = get(self.cleaned_data, 'data_raw')
        if not (data_file or data_raw):
            self.add_error(None, forms.ValidationError('Please provide either file or raw data.'))
        return super(DatasetUploadForm, self).clean()

    def clean_data_file(self):
        file = self.cleaned_data['data_file']
        if file is not None:
            file_type = magic.from_buffer(file.read(1024), mime=True)
            file.seek(0)
            if not file_type.startswith('text/'):
                self.add_error('data_file', 'Uploaded file must be a text file.')
        return file

    def get_form_layout(self) -> Layout:
        return Layout(
            Div(
                Field('title', css_class='form-control'),
                css_class='row my-3',
            ),
            Div(
                Field('data_file', css_class='form-control'),
                css_class='row my-3',
            ),
            Div(
                Field('data_raw', css_class='form-control'),
                css_class='row my-3',
            ),
            Div(
                Div(
                    Field('relevant_column', css_class='form-control'),
                    css_class='col-12 col-md-6',
                ),
                Div(
                    Div(Field('has_header', css_class='form-check-input'), css_class='form-check'),
                    css_class='col-12 col-md-6',
                ),
                css_class='row my-3 align-items-end',
            ),
            Submit(name='submit', value='Send form', css_id='id_submit'),
        )

    @property
    def form_id(self) -> str:
        return 'form-upload-dataset'

crispy_forms_bootstrap5/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout


class CrispyFormMixin:
    def __init__(self, *args, **kwargs):
        super(CrispyFormMixin, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        self.helper.form_method = 'POST'
        self.helper.form_id = self.form_id
        self.helper.use_custom_control = False
        self.helper.layout = self.get_form_layout()

    def get_form_layout(self) -> Layout:
        raise NotImplementedError

    @property
    def form_id(self) -> str:
        return 'id_form'

benford/views.py
from django.shortcuts import redirect
from django.views.generic import FormView, DetailView, ListView

from benford.analyzer import BenfordAnalyzer
from benford.forms import DatasetUploadForm
from benford.models import Dataset, DatasetRow


class DashboardView(ListView):
    template_name = 'benford/dashboard.html'
    queryset = Dataset.objects.all()
    paginate_by = 10


class DatasetUploadView(FormView):
    template_name = 'benford/form.html'
    form_class = DatasetUploadForm

    def __init__(self, *args, **kwargs):
        self.object = None
        super(DatasetUploadView, self).__init__(*args, **kwargs)

    def create_dataset(self, form):
        benford_analyzer = BenfordAnalyzer.create_from_form(form)
        self.object = benford_analyzer.save()

    def form_valid(self, form):
        self.create_dataset(form)
        return redirect('benford:dataset_detail', slug=self.object.slug)


class DatasetDetailView(DetailView):
    template_name = 'benford/dataset/detail.html'
    model = Dataset
    analyzer: BenfordAnalyzer = None

    def get_object(self, queryset=None):
        obj = super(DatasetDetailView, self).get_object(queryset=queryset)
        self.analyzer = BenfordAnalyzer.create_from_model(obj)
        return obj

    def get_context_data(self, **kwargs):
        self.object: Dataset
        ctx = super(DatasetDetailView, self).get_context_data(**kwargs)
        ctx['title'] = self.object.title
        ctx['significant_digits'] = self.object.significant_digits.all().order_by('digit')
        ctx['analyzer'] = self.analyzer
        ctx['dataset_rows'] = self.get_erroneous_dataset_rows()
        return ctx

    def get_erroneous_dataset_rows(self):
        return DatasetRow.objects.filter(
            dataset=self.analyzer.dataset, has_error=True,
        ).order_by('line')


class DatasetRowListView(ListView):
    paginate_by = 100
    template_name = 'benford/dataset/browse_data.html'
    dataset = None

    def get(self, *args, **kwargs):
        self.dataset = Dataset.objects.get(slug=self.get_slug())
        return super(DatasetRowListView, self).get(*args, **kwargs)

    def get_queryset(self):
        return DatasetRow.objects.filter(dataset=self.dataset).order_by('line')

    def get_context_data(self, *args, **kwargs):
        ctx = super(DatasetRowListView, self).get_context_data(*args, **kwargs)
        ctx['title'] = self.get_view_title()
        ctx['dataset'] = self.dataset
        ctx['slug'] = self.get_slug()
        return ctx

    def get_slug(self):
        return self.kwargs['slug']

    def get_view_title(self):
        return f'Browse: {self.dataset.display_title()}'

benford/templates/benford/dashboard.html
{% extends "base.html" %}
{% load pagination_tags %}

{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12">
        {% if page_obj %}
          <table id="table-datasets" class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th>Created at</th>
            </tr>
            </thead>
            <tbody>
            {% for dataset in page_obj %}
              <tr>
                <td>
                  <a href="{{ dataset.get_absolute_url }}">
                    {{ dataset.display_title }}</a>
                </td>
                <td>{{ dataset.created_at }}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>

          {% pagination paginator page_obj %}
        {% else %}
          <div class="row justify-content-center">
            <div class="col-12 col-md-6 text-center py-5">
              There are currently no datasets in the database.
              <div class="p-3">
                <a href="{% url 'benford:upload_dataset' %}"
                   class="btn btn-primary btn-lg">
                  Go and create one!</a></div>
            </div>
          </div>
        {% endif %}

      </div>
    </div>
  </div>
{% endblock %}

benford/templates/benford/dataset/browse_data.html
{% extends "base.html" %}
{% load benford_tags pagination_tags %}

{% block content %}
  <div class="container-fluid py-3">
    <div class="row align-items-center">
      <div class="col-auto">
        <a href="{% url 'benford:dataset_detail' dataset.slug %}"
           class="text-secondary">{% include "_back_arrow.html" %}</a>
      </div>
      <div class="col"><h1>{{ dataset.display_title }}</h1></div>
    </div>
    <h2>Browse data</h2>

    {% if page_obj %}

      {% pagination paginator page_obj %}

      <div class="my-3">
        <table id="table-dataset-rows" class="table table-hover">
          {% for row in page_obj %}
            <tr{% if row.has_error %} class="text-danger"{% endif %}>
              <td>{{ row.line }}</td>
              {% for col in row.data %}
                <td>{{ col }}</td>
              {% endfor %}
            </tr>
          {% endfor %}
        </table>
      </div>

      {% pagination paginator page_obj %}

    {% else %}
      <div class="row justify-content-center">
        <div class="col-auto text-center">
          <div class="text-secondary display-6 m-5">
            No data available.
          </div>
          <a href="{% url 'benford:dataset_detail' slug=slug %}"
             class="btn btn-primary">
            Back to dataset view</a>
        </div>
      </div>
    {% endif %}

  </div>

{% endblock %}

benford/templates/benford/dataset/detail.html
{% extends "base.html" %}
{% load benford_tags %}

{% block content %}
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-auto">
        <a href="{% url 'benford:dashboard' %}" class="text-secondary">
          {% include "_back_arrow.html" %}</a>
      </div>
      <div class="col"><h1>{{ analyzer.dataset.display_title }}</h1></div>
    </div>

    <div class="row mt-3">
      <div class="col-12 col-md-6">
        <div class="py-3 text-center">
          {% with is_compliant=analyzer.is_compliant_with_benford_law %}
            Is this dataset compliant with Benford's Law?
            <div class="display-6">
              <div class="badge {% if is_compliant %}bg-success{% else %}bg-danger{% endif %}">
                {{ is_compliant|yesno|upper }}</div>
            </div>
          {% endwith %}
        </div>

        <table id="table-dataset-summary" class="table my-3">
          <thead>
          <tr>
            <th>Digit</th>
            <th>Occurences</th>
            <th>Percent</th>
            <th>Expected</th>
          </tr>
          </thead>
          <tbody>
          {% for significant_digit in analyzer.get_summary %}
            <tr>
              <td>{{ significant_digit.digit }}</td>
              <td>{{ significant_digit.occurences }}</td>
              <td>{{ significant_digit.percentage }}</td>
              <td>{{ significant_digit.expected_percentage }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>

        <div class="my-3">
          <a href="{% url 'benford:dataset_rows' slug=dataset.slug %}"
             class="btn btn-primary btn-block">Browse data</a>
        </div>
        {#        <div>#}
        {#          The chi-squared test statistic = {{ analyzer.get_chisq_test_statistic }}#}
        {#        </div>#}
      </div>

      <div class="col-12 col-md-6 col-graph">
        {% graph analyzer %}
      </div>
    </div>

  </div>

  {% if dataset_rows.exists %}
    <div class="container-fluid mt-3">
      <h2>Erroneous rows</h2>

      <p>There were some rows in the dataset that couldn't be processed
        correctly. They are not included in the above analysis.</p>

      <div class="row">
        <div class="col">
          <table class="table">
            <tbody>
            {% for row in dataset_rows %}
              <tr class="text-danger">
                <td>{{ row.line }}</td>
                {% for col in row.data %}
                  <td>{{ col }}</td>
                {% endfor %}
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

benford/templates/benford/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12 col-md-6">
        <h1>Upload new dataset</h1>
        {% crispy form %}
      </div>
    </div>
  </div>
{% endblock %}

benford/templates/benford/templatetags/graph.html
<img alt="" src="{{ img_src }}" class="graph">

pagination/templates/pagination/templatetags/pagination.html
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-auto">
      <nav class="nav-pagination">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link"
                 href="?page=1">First</a>
            </li>
            <li class="page-item">
              <a class="page-link"
                 href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
          {% endif %}

          {% for p in page_number_range %}
            <li class="page-item {% ifequal page_obj.number p %}active{% endifequal %}">
              <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
          {% endfor %}

          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link"
                 href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"
                 href="?page={{ paginator.num_pages }}">Last ({{ paginator.num_pages }})</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>

theme/templates/_back_arrow.html
<svg width="1.8em" height="1.8em" viewBox="0 0 16 16" class="bi bi-arrow-left-square-fill" fill="currentColor"
     xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd"
        d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.354 10.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L6.207 7.5H11a.5.5 0 0 1 0 1H6.207l2.147 2.146z"/>
</svg>

theme/templates/base.html
{% load sass_tags %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% if title %}{{ title }} | {% endif %}Frank Benford's Law Project</title>
  <meta name="description" content="A programming challenge">
  <meta name="author" content="Marek Naskręt">
  <link rel="stylesheet" href="{% sass_src "scss/theme.scss" %}" type="text/css">
</head>

<body>

<nav id="main-navbar" class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a href="{% url 'benford:dashboard' %}" class="nav-link">
            Home</a></li>
        <li class="nav-item">
          <a href="{% url 'benford:upload_dataset' %}" class="nav-link">
            Upload new dataset</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block content %}{% endblock %}

</body>
</html>